# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.1

# ansible用のorbsを追加
  ansible-playbook: orbss/ansible-playbook@0.0.5

jobs:
  execute-cloudformation:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
      - run:
          name: deploy Cloudformation
          command: |
            aws cloudformation deploy --stack-name sampleStackFormationCI --template-file infratemp.yml
  execute-ansible:
    executor: ansible-playbook/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "85:e8:61:41:46:f7:ae:e2:92:fd:d7:cc:1f:e4:e1:fd"
      - ansible-playbook/install:
          version: 2.10.3
          
# 下記は、ファイルパス記述
      - ansible-playbook/playbook:
          playbook: ansible/playbook.yml
          inventory: ANAIBLE_INVENTORY
          playbook-options: "-u ec2-user --private_key ~/.ssh/id_rsa -i ansible/hosts/inventory"



# workflowsをリポジトリと同じ名称にしておく
workflows:
  circletest:
    jobs:
      - execute-cloudformation
      - execute-ansible:
          requires:
            - "execute-cloudformation"